### ISSUE TITLE
[Anon] Bug report: Scum and Villainy - SWXW.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/swxwing#15]
**File:** Scum and Villainy - SWXW.catz

**BattleScribe version:** 1.15.07

**Platform:** Linux

**Dropbox:** No

**Description:** Tactician, Outlaw Tech and Targeting Coordinator are limited to 1, but should be unlimited (-1).

**Comment by XWingDrLucky** [comment]
These are correctly limited to one per ship.  All share the "Limited" keyword (Outlaw Tech and Targeting Coordinator by card text, Tactician by errata in the official FAQ), which limits them to one per ship.  These three upgrades should not be unlimited.
