### ISSUE TITLE
[Anon] Bug report: Empire - SWXW.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/swxwing#16]
**File:** Empire - SWXW.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Sienar Test Pilot for the new TAP should be 16 points, not 14.

**Comment by XWingDrLucky** [comment]
I've already fixed this as part of some other additions I'm working on today.  This will be updated and correct in the public version by the end of the day.
