### ISSUE TITLE
How do I download data files 

### ISSUE THREAD

**Issue by Wolfofeinherjar** [BSData/swxwing#19]
Just like the subject said, how do I download the data files

**Comment by amis92** [comment]
Go to http://battlescribedata.appspot.com/#/repos and:
* on mobile: click on repo you want: that'll download the .bsi file, open it in BattleScribe; that'll download the files you want and add the repo to index so you can easily get updates;
* on desktop: right-click on repo you want, `Copy Link` (or similar), open BattleScribe, `Manage Data`, paste in the field on the top, click `Add`, `Update Data`.

Voila!
