### ISSUE TITLE
[Anon] Bug report: Empire - SWXW.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/swxwing#20]
**File:** Empire - SWXW.catz

**BattleScribe version:** 2.00.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Imperial Raider Single Turbolasers hardpoint is listed as "no cost", when they actually cost 8 points.

**Comment by XWingDrLucky** [comment]
I've already fixed this locally. It will be corrected in the next release
(probably Monday evening).

**Comment by XWingDrLucky** [comment]
Corrected in commit 411.  Release will happen later today.
