### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by BlueSeven** [BSData/swxwing#30]
I don't think anyone is updating this anymore so I may as well do it alongside the Armada data.
Could you also check the automation is all correct as the Armada one was inactive a similar amount of time and needed it all fixing.
Thanks.

**Comment by Mad-Spy** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/3817889604)
:robot: Invited @BlueSeven with **push** access. Invite can be accepted on https://github.com/BSData/swxwing/invitations
